services:
  memcached:
    restart: always
    image: "memcached"
    container_name: "memcached"

  mongo:
    restart: always
    image: "mongo"
    container_name: "mongo"
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ejudge_net

  algocode:
    build: 
      context: .
    restart: always
    image: "algocode:latest"
    container_name: "algocode"
    ports:
      - "127.0.0.1:8002:80"
    volumes:
      - ejudge_data:/home/judges
      - algocode_data:/home/algocode
    depends_on:
      - memcached
      - mongo
    networks:
      - ejudge_net

volumes:
  ejudge_data:
    name: ejudge_data
  mongo_data:
    name: mongo_data
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mongo
  algocode_data:
    name: algocode_data
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/algocode

networks:
  ejudge_net:
    name: ejudge_net
