services:
  algocode:
    build: 
      context: .
    restart: always
    image: algocode:latest
    container_name: 'algocode'
    ports:
      - "127.0.0.1:8002:80"
    volumes:
      - algocode_data:/app
      - ejudge_data:/home/judges:ro
    networks: 
      - ejudge-net

volumes:
  algocode_data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/ejudge/data/algocode
  ejudge_data:
    external: true

networks:
  ejudge-net:
    external: true
