# Generated by Django 4.2.10 on 2025-08-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_pagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('headers', models.TextField(blank=True, default='{}')),
                ('body', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='courses.formbuilder')),
            ],
        ),
    ]
